name: Update Rankings

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *'  # Runs every hour (adjust as needed)
  workflow_dispatch:  # Enables manual runs

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set Up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: pip install pandas loguru openpyxl

      - name: Download Excel File from Google Drive
        run: |
          curl -L -o hks_scores.xlsx "https://docs.google.com/uc?export=download&id=11YZNb0w0DUDN9D2DPCQO3UDKPbwi05Qq"

      - name: Run Ranking Script
        run: python hks_ranking.py

      - name: Commit and Push Results
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add rankings.json
          git commit -m "Auto-update rankings" || echo "No changes to commit"
          git push || echo "No changes to push"