name: Update Rankings

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *'  # Runs every hour (adjust as needed)
  workflow_dispatch:  # ✅ Enables manual runs

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set Up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: pip install pandas loguru openpyxl

      - name: Run Ranking Script
        run: python hks_ranking.py

      - name: Move `rankings.json` to Root
        run: |
          mv rankings.json rankings.json || true
          mv ranking.xlsx ranking.xlsx || true

      - name: Commit and Push Results
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add rankings.json ranking.xlsx
          git diff --cached --quiet || git commit -m "Auto-update rankings"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git main