name: Update Rankings

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  workflow_dispatch:  # ✅ Enables manual runs

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set Up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: pip install pandas loguru openpyxl

      - name: Run Ranking Script
        run: python hks_ranking.py

      - name: Commit and Push Results
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add -f rankings.json  # ✅ Force add the ignored file
          git add ranking.xlsx  # Ensure the Excel file is added too
          git commit -m "Auto-update rankings" || echo "No changes to commit"
          git push